version: "3.7"

services:
  cake-wallet:
    build:
      context: ./app
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - cake-wallet-data:/opt/app

volumes:
  cake-wallet-data: